Amazon = ("a.a-link-nav-icon")
Create account = ("h1.a-spacing-small")
Your name = ("input#ap_customer_name")
Email = ("input#ap_email")
Password = ("input#ap_password_check")
Re-enter password ("input#ap_password_check")
Create your Amazon account = ("input#continue")
Conditions of use = ("a[href*='condition_of_use']")
Privacy Notice = ("a[href*='privacy_notice']")